// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX2ZETdNfwEXqiwoQYjEEy62ccj8R9xdA',
    appId: '1:55373499767:web:b08a9c518a5b08bc2ae572',
    messagingSenderId: '55373499767',
    projectId: 'fir-app-50364',
    authDomain: 'fir-app-50364.firebaseapp.com',
    storageBucket: 'fir-app-50364.appspot.com',
    measurementId: 'G-2CQD2R3H4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2wG9wIlcHs1A4D84JiP4GnnniSWEwlZ0',
    appId: '1:55373499767:android:23b558b8bd7139c42ae572',
    messagingSenderId: '55373499767',
    projectId: 'fir-app-50364',
    storageBucket: 'fir-app-50364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXtOJlKlc0pIL_-Io65vVW7jaRJl4kB1Q',
    appId: '1:55373499767:ios:55786e304f44c0882ae572',
    messagingSenderId: '55373499767',
    projectId: 'fir-app-50364',
    storageBucket: 'fir-app-50364.appspot.com',
    iosClientId: '55373499767-f7o2eif3dfe1ri5j1fk206a395rqqa5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXtOJlKlc0pIL_-Io65vVW7jaRJl4kB1Q',
    appId: '1:55373499767:ios:55786e304f44c0882ae572',
    messagingSenderId: '55373499767',
    projectId: 'fir-app-50364',
    storageBucket: 'fir-app-50364.appspot.com',
    iosClientId: '55373499767-f7o2eif3dfe1ri5j1fk206a395rqqa5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
